version: '3.8' # Wersja składni Docker Compose

services:
  # Serwis dla bazy danych PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: go_postgres_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-mydatabase}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Serwis dla Twojej aplikacji Go
  backend_app:
    build: .
    container_name: go_backend_app
    ports:
      - "${GO_SERVER_PORT:-8080}:${GO_SERVER_PORT:-8080}"
    environment:
      DATABASE_URL: host=db user=${DB_USER:-postgres} password=${DB_PASSWORD:-password} dbname=${DB_NAME:-mydatabase} port=5432 sslmode=disable TimeZone=Europe/Warsaw
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

# Definicja wolumenów
volumes:
  db_data: